# Generated by Django 4.2.6 on 2023-10-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcollector_app', '0003_accessory_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
    ]
