# Generated by Django 4.2.6 on 2023-10-25 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogcollector_app', '0004_alter_accessory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={},
        ),
    ]
