# Generated by Django 4.2.6 on 2023-10-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogcollector_app', '0005_alter_accessory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='accessories',
            field=models.ManyToManyField(to='dogcollector_app.accessory'),
        ),
    ]
